### ISSUE TITLE
Data version 2018 (package v0.2) roadmap

### ISSUE THREAD

**Issue by psolymos** [ABbiodiversity/cure4insect#34]
Updating data and package is under way, here is the roadmap:

### General

- Spatial predictions will use 2016 HFI for **all** species,
- veg/soil labels slightly altered but still referring to v6.* of the backfilled layer,
- new HF labels: `TameP` and `RoughP` that were previously part of `Crop`.

### Common data

- [x] `XY` **stayed the same**
- [x] `QT2KT` **stayed the same**
- [x] `KT` **LUF region issue fixed but mostly stayed the same**
- [x] `KA_2016` **added**
- [x] `SP` **lookup updated**
- [x] `CF` **coefs for plotting updated**
- [x] `VER` **updated**
- [x] `CFbirds`

### Species results

- [x] `/sector` **updated -- needs checking**
- [x] `/spclim` **updated -- needs checking**
- [x] `/boot` **updated -- needs checking**

### Other

- [x] Internal function added to figure out footprint version depending on version and taxon
- [x] plotting functions need to be updated for new land cover classes, recognize version
- [x] mammals: unchanged coefficients applied to 2016 HFI

**Comment by psolymos** [comment]
For mammals, here is the proposal:

- [x] develop land cover crosswalk for versions
- [x] match the coefficients with the new labels (this means repeating Cultivation for pasture)
- [x] use these coefficients and the spatial component to update the predictions (`/sector`) to 2016 HFI as the rest of the species
- [x] leave the `/boot` results as is (it is based on 2014 HFI but most of the uncertainty is coming other sources)
- [x] `/spclim` results unchanged
